### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by Kraignos** [fdnhkj/react-native-dynatrace#1]
Can you publish version 0.0.2 on npm so that we have the natives modules updated with their methods? What we get so far is an empty module definition which was the case at the time you've published version 0.0.1 I presume. Thanks.

**Comment by odemolliens** [comment]
*bump*

**Comment by fdnhkj** [comment]
Version 0.0.2 is published on npm

**Comment by odemolliens** [comment]
Thanks @fdnhkj.
